// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using albumica.Entities;

#nullable disable

namespace albumica.Entities.Migrations.Sqlite
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20230714132417_AddImageImport")]
    partial class AddImageImport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("MediaTag", b =>
                {
                    b.Property<int>("MediaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("media_id");

                    b.Property<int>("TagsTagId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tags_tag_id");

                    b.HasKey("MediaId", "TagsTagId")
                        .HasName("pk_media_tag");

                    b.HasIndex("TagsTagId")
                        .HasDatabaseName("ix_media_tag_tags_tag_id");

                    b.ToTable("media_tag", (string)null);
                });

            modelBuilder.Entity("MediaUser", b =>
                {
                    b.Property<int>("BasketMediaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("basket_media_id");

                    b.Property<int>("UsersUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("users_user_id");

                    b.HasKey("BasketMediaId", "UsersUserId")
                        .HasName("pk_media_user");

                    b.HasIndex("UsersUserId")
                        .HasDatabaseName("ix_media_user_users_user_id");

                    b.ToTable("media_user", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("TEXT")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("TEXT")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("albumica.Entities.Media", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("media_id");

                    b.Property<long?>("Created")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created");

                    b.Property<bool>("Hidden")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hidden");

                    b.Property<string>("Import")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("import");

                    b.Property<bool>("IsVideo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_video");

                    b.Property<string>("Original")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("original");

                    b.Property<string>("Preview")
                        .HasColumnType("TEXT")
                        .HasColumnName("preview");

                    b.Property<string>("SHA256")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sha256");

                    b.HasKey("MediaId")
                        .HasName("pk_media");

                    b.ToTable("media", (string)null);
                });

            modelBuilder.Entity("albumica.Entities.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("tag_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name_normalized");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order");

                    b.HasKey("TagId")
                        .HasName("pk_tags");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("albumica.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<long?>("Disabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("disabled");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_admin");

                    b.Property<long?>("LastUpload")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_upload");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MediaTag", b =>
                {
                    b.HasOne("albumica.Entities.Media", null)
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_tag_media_media_id");

                    b.HasOne("albumica.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_tag_tags_tags_tag_id");
                });

            modelBuilder.Entity("MediaUser", b =>
                {
                    b.HasOne("albumica.Entities.Media", null)
                        .WithMany()
                        .HasForeignKey("BasketMediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_user_media_basket_media_id");

                    b.HasOne("albumica.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_user_users_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
